# Generated by Django 3.0.5 on 2020-04-12 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 4, 12, 0, 25, 46, 945842, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
